# Measuring Hate Speech

Creating `text_data.csv` and `annotations.csv` for Measuring Hate Speech dataset.

Preprocessing is applie: removing duplicates.

In [87]:
%load_ext autoreload
%autoreload 2

import os
import sys
sys.path.append('../../../')

import pandas as pd
from tqdm.auto import tqdm

from datasets import load_dataset
from multitask_nlp.settings import DATASETS_DIR

tqdm.pandas()

dataset_path = DATASETS_DIR / 'measuring_hate_speech'

isExist = os.path.exists(dataset_path)

if not isExist:
    os.makedirs(dataset_path)
    print("The new directory is created!")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Loading dataset

In [81]:
dataset = load_dataset("ucberkeley-dlab/measuring-hate-speech")

Using custom data configuration ucberkeley-dlab--measuring-hate-speech-7cb9b0b8e4d0e1dd
Reusing dataset parquet (C:\Users\wojte\.cache\huggingface\datasets\parquet\ucberkeley-dlab--measuring-hate-speech-7cb9b0b8e4d0e1dd\0.0.0\0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901)

  0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
df = dataset['train'].to_pandas()

In [26]:
df.to_csv(dataset_path / 'data_raw.csv', index=False)

In [88]:
df =  pd.read_csv(dataset_path / 'data_raw.csv')

## Preprocessing data

In [19]:
len(df.comment_id.unique())

39565

In [15]:
df[df.comment_id == 1]['text']

1064     White people are trash.
23298    White people are trash.
50410    White people are trash.
70119    White people are trash.
Name: text, dtype: object

In [17]:
len(df.text.unique())

39565

In [31]:
df.describe()

,comment_id,annotator_id,platform,sentiment,respect,insult,humiliate,status,dehumanize,violence,...,hatespeech,hate_speech_score,infitms,outfitms,annotator_severity,std_err,annotator_infitms,annotator_outfitms,hypothesis,annotator_age
count,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.00000,135556.000000,135556.000000,135556.000000,135556.000000,...,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135556.000000,135451.000000
mean,23530.416138,5567.097812,1.281352,2.954307,2.828875,2.56331,2.278638,2.698575,1.846211,1.052045,...,0.744733,-0.567428,1.034322,1.001052,-0.018817,0.300588,1.007158,1.011841,0.014589,37.910772
std,12387.194125,3230.508937,1.023542,1.231552,1.309548,1.38983,1.370876,0.898500,1.402372,1.345706,...,0.932260,2.380003,0.496867,0.791943,0.487261,0.236380,0.269876,0.675863,0.613006,11.641276
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-8.340000,0.100000,0.070000,-1.820000,0.020000,0.390000,0.280000,-1.578693,18.000000
25%,18148.000000,2719.000000,0.000000,2.000000,2.000000,2.00000,1.000000,2.000000,1.000000,0.000000,...,0.000000,-2.330000,0.710000,0.560000,-0.380000,0.030000,0.810000,0.670000,-0.341008,29.000000
50%,20052.000000,5602.500000,1.000000,3.000000,3.000000,3.00000,3.000000,3.000000,2.000000,0.000000,...,0.000000,-0.340000,0.960000,0.830000,-0.020000,0.340000,0.970000,0.850000,0.110405,35.000000
75%,32038.250000,8363.000000,2.000000,4.000000,4.000000,4.00000,3.000000,3.000000,3.000000,2.000000,...,2.000000,1.410000,1.300000,1.220000,0.350000,0.420000,1.170000,1.130000,0.449555,45.000000
max,50070.000000,11142.000000,3.000000,4.000000,4.000000,4.00000,4.000000,4.000000,4.000000,4.000000,...,2.000000,6.300000,5.900000,9.000000,1.360000,1.900000,2.010000,9.000000,0.987511,81.000000

In [30]:
df

,comment_id,annotator_id,platform,sentiment,respect,insult,humiliate,status,dehumanize,violence,...,annotator_religion_hindu,annotator_religion_jewish,annotator_religion_mormon,annotator_religion_muslim,annotator_religion_nothing,annotator_religion_other,annotator_sexuality_bisexual,annotator_sexuality_gay,annotator_sexuality_straight,annotator_sexuality_other
0,47777,10873,3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,39773,2790,2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
2,47101,3379,3,4.0,4.0,4.0,4.0,4.0,4.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,43625,7365,3,2.0,3.0,2.0,1.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
4,12538,488,0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135551,37080,8590,2,1.0,1.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
135552,22986,8303,2,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,False,True,True,False,False,False
135553,21008,6207,2,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
135554,22986,7886,2,2.0,0.0,0.0,0.0,2.0,0.0,0.0,...,False,False,False,False,True,False,False,False,True,False
135555,14785,6897,0,4.0,4.0,4.0,2.0,2.0,2.0,3.0,...,False,False,False,False,False,False,False,False,True,False

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135556 entries, 0 to 135555
Columns: 131 entries, comment_id to annotator_sexuality_other
dtypes: bool(103), float64(19), int32(2), int8(1), object(6)
memory usage: 40.3+ MB

In [62]:
columns_to_preserve = ['comment_id', 'annotator_id', 'platform', 'sentiment', 'respect',
       'insult', 'humiliate', 'status', 'dehumanize', 'violence',
       'genocide', 'attack_defend', 'hatespeech', 'hate_speech_score',
       'text']

df = df[columns_to_preserve]

In [73]:
texts_df = df[['comment_id', 'text']]
texts_df = texts_df.rename(columns={'comment_id': 'text_id'})
texts_df = texts_df.drop_duplicates()

In [74]:
texts_df

        text_id                                               text
0         47777  Yes indeed. She sort of reminds me of the elde...
1         39773  The trans women reading this tweet right now i...
2         47101  Question: These 4 broads who criticize America...
3         43625  It is about time for all illegals to go back t...
4         12538  For starters bend over the one in pink and kic...
...         ...                                                ...
135546    26287  🔥PUBG JAPAN SERIES 🔥Grade2 Day2 6/7 <Round8> 1...
135547    14785  لا تتشمت الرجال مسكين يعاني كس امه 😂. يقول يال...
135549    30588  Umar khalid, sahela rashid, kanhiyan kumar जैस...
135550    21008  @AbeShinzo @realDonaldTrump @shinzoabe 独裁者は行きま...
135551    37080  عاجل سماحة #السيد_عبدالملك_بدرالدين_الحوثي  نص...

[39565 rows x 2 columns]

In [75]:
annotations_df = df.copy()
annotations_df = annotations_df.drop(['platform', 'text'], axis=1)
annotations_df = annotations_df.rename(columns={'comment_id': 'text_id'})

In [94]:
annotations_df.dtypes

text_id                int32
annotator_id           int32
sentiment            float64
respect              float64
insult               float64
humiliate            float64
status               float64
dehumanize           float64
violence             float64
genocide             float64
attack_defend        float64
hatespeech           float64
hate_speech_score    float64
dtype: object

In [79]:
texts_df.to_csv(dataset_path / 'data.csv', index=False)
annotations_df.to_csv(dataset_path / 'annotations.csv', index=False)